/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseBadge: typeof import('./components/BaseBadge.vue')['default']
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseError: typeof import('./components/BaseError.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    BaseLabel: typeof import('./components/BaseLabel.vue')['default']
    BaseLayout: typeof import('./components/BaseLayout.vue')['default']
    BaseLoader: typeof import('./components/BaseLoader.vue')['default']
    BaseLogo: typeof import('./components/BaseLogo.vue')['default']
    BaseMenuButton: typeof import('./components/BaseMenuButton.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    BaseProgress: typeof import('./components/BaseProgress.vue')['default']
    BaseSelect: typeof import('./components/BaseSelect.vue')['default']
    BaseSeparator: typeof import('./components/BaseSeparator.vue')['default']
    BaseSkeleton: typeof import('./components/BaseSkeleton.vue')['default']
    BaseSwitch: typeof import('./components/BaseSwitch.vue')['default']
    BaseTextArea: typeof import('./components/BaseTextArea.vue')['default']
    ConfirmModal: typeof import('./components/ConfirmModal.vue')['default']
    CreateProjectModal: typeof import('./components/CreateProjectModal.vue')['default']
    DashboardItem: typeof import('./components/DashboardItem.vue')['default']
    EditSongModal: typeof import('./components/EditSongModal.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    ProjectItem: typeof import('./components/ProjectItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsAdvanced: typeof import('./components/SettingsAdvanced.vue')['default']
    SettingsAppearance: typeof import('./components/SettingsAppearance.vue')['default']
    SettingsGeneral: typeof import('./components/SettingsGeneral.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    SideBarRow: typeof import('./components/SideBarRow.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    ToastContainer: typeof import('./components/ToastContainer.vue')['default']
  }
}
